### ISSUE TITLE
There are 2 Cart buttons on top

### ISSUE THREAD

**Issue by TartejBrothers** [umair763/ecommerce-website#1]
- There are 2 cart buttons on top, 
![image](https://github.com/umair763/ecommerce-website/assets/112921727/36b61043-81e1-43eb-a822-b61043062a04)

## UI improvement
- Add Some padding on the top of the navbar, might make it look better.

**Comment by umair763** [comment]
I see there are some things that really need improvements and changes, you improve it and optimize the issues. i am giving control to you as I am a beginner so that's why I am asking you.

**Comment by TartejBrothers** [comment]
Ok sure, give me sometime, I m busy with some work, I will get back to you in 2 days.

**Comment by TartejBrothers** [comment]
Hi, I was working on the website, I have made some changes but I can't properly work on it as you have not uploaded the images. Please do push them to GitHub.
